<div class="jumbotron">
  <h1>Fixed navbar</h1>
  <h4>Bootstrap 4 example template</h4>
  <p class="lead">This example is a quick exercise to illustrate how fixed to top navbar works. As you scroll, it will remain fixed to the top of your browser's viewport.</p>
  <a class="btn btn-lg btn-primary" href="https://getbootstrap.com/docs/4.0/components/navbar/" role="button">View navbar docs &raquo;</a>
</div>
