<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="./" title="<?= $description ?>"><?= $title ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
<?php foreach ($menu as $m) { ?>
      <li class="nav-item<?= ' ' . $m['class'] ?>">
        <a class="nav-link" href="<?= $m['href'] ?>"><?= $m['title'] ?>
<?php if ($m['class'] == 'active') { ?>
<span class="sr-only">(current)</span>
<?php } ?></a>
      </li>
<?php } ?>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
